### PR TITLE
Implement include_tags and include_vmid

### LINKED ISSUE #188: Introduce include_{vmid/tags} options
Basically the inverse for the `exclude_{vmid/tags}` options that already exist.

As I currently have multiple exporters on some hosts (eg.  mysql/postgres exporters), I would like to be able to run multiple instances of the pve-sd so I can then use the relabeling to append a different port.
Since only a few selected machines would need to be in that list, using the `exclude` mechanics would be tiresome, as each new host would need to be added.

Introducing a `include_{vmid/tags}` option would allow creating such a setup very easily.

I would probably do a chaining of the `include`/`exclude` options, so that a VM could have the tags `postgres,unmonitored` and would still be excluded by the following config
```
include_tags:
  - postgres
 exclude_tags:
  - unmonitored
```

I should find some time this week, to make a WIP pull request for this. Any input is welcome.

### PR DESCRIPTION
**Pull request by peschmae**
- Add tests to verify empty lists work
- Add tests for exclude & include tags at the same time

Fixes #188

### CODE REVIEW

**Comment by peschmae** [comment]
ToDo: Docs

**Comment by xoxys** [comment]
No strong opinion yet. `exclude_*` will always win? Shouldn't `obj["tags"]` always a string? Why do we check  `isinstance(obj["tags"], dict)` now?

**Comment by peschmae** [comment]
`exclude` always wins/takes presedence (is now also documented)

If `obj["tags"]` is not set at all python will return an empty dict, this way it's possible to chain the `isdijoint` check with the check if tags are even present.
Thinking about it again a check if the element is empty should be enough, and might alsoo be more future proof, if proxmox decied to return an empty tag list at some point###

**Comment by xoxys** [comment]
That is confusing me even more :) According to the syntax we have already in https://github.com/thegeeklab/prometheus-pve-sd/blob/611d182e5ae2382c4a482f242eb6423a5af349e1/prometheuspvesd/discovery.py#L174-L177, why not just use:

```
        if (
                len(self.config.config["include_tags"]) > 0 and
                isinstance(obj["tags"], str) and
                set(obj["tags"].split(",")).isdisjoint(self.config.config["include_tags"])
            ):
                continue
```

Even an empty string should not result in an issue as the `split` will result in an empty list.

**Comment by peschmae** [comment]
My idea is to only list VMs that have a tag matching the include list.
If no tags are present on a VM, but the `include_tags` option is set, they need to be skipped as well.

Since python returns an empty dict if `obj["tags"]` doesn't exist (wasn't part of the answer from the proxmox api), I've added the dict check in the beginning.
If tags are present on the obj, `obj["tags"]` will be a string.

Checking if `obj["tags"]` evaluates to False handles the case where it's not present in the api response (empty dict), and also works if proxmox suddenly returns a empty string if no tags are set.

**Comment by peschmae** [comment]
> That is confusing me even more :) According to the syntax we have already in https://github.com/thegeeklab/prometheus-pve-sd/blob/611d182e5ae2382c4a482f242eb6423a5af349e1/prometheuspvesd/discovery.py#L174-L177, why not just use:
> 
> ```Python
>     if (
>             len(self.config.config["include_tags"]) > 0
>             and isinstance(obj["tags"], str)
>             and set(obj["tags"].split(",")).isdisjoint(self.config.config["include_tags"])
>         ):
>             continue
> ```
> 
> Even an empty string should not result in an issue, as the `split` will result in an empty list.


This would result in VMs without any tags at all, to be included even though they don't match the `include_tags` list

**Comment by xoxys** [comment]
> This would result in VMs without any tags at all, to be included even though they don't match the `include_tags` list

Why that? VMs without any tags means empty `obj["tags"]` right? And an empty `obj["tags"]` should always result in `isdisjoint == True` and skipped for this reason. But maybe I'm wrong :thinking:

**Comment by peschmae** [comment]
> > This would result in VMs without any tags at all, to be included even though they don't match the `include_tags` list
> 
> Why that? VMs without any tags means empty `obj["tags"]` right? And an empty `obj["tags"]` should always result in `isdisjoint == True` and skipped for this reason. But maybe I'm wrong thinking

`isinstance(obj["tags"], str)` will return False if `obj["tags"]` is not present on the API, resulting in the loop continuing, without checking if the list is disjoint

With `isinstance(obj["tags"], dict)` (or `bool(obj["tags"]) is False`) we check that the tags are not empty, and only then the disjoint is checked.
And those need to be joined with an `OR` since if it's a dict, the `split` would throw an exception

**Comment by peschmae** [comment]
I've implemented quite a few tests for this feature, since the different cases (no tags set, tag set but not matching, multiple include tags set, include & exclude tags set) are numerous as well, and using these as the verification that the implementation works, I think the solution with `bool(obj["tags"]) is False` is quite nice and more future proof than checking for a dict

**Comment by xoxys** [comment]
Ok, let me know if you are ready :)

**Comment by peschmae** [comment]
I think it's looking good and working as intended. I did some check against my home setup as well, and there it works fine.

By mistake I commited a documentation change for the prometheus operator into this branch, but I think that should be fine too.

**Comment by xoxys** [comment]
Thanks again, and sorry for the delay.

**Comment by xoxys** [comment]
@peschmae you have committed your out file https://github.com/thegeeklab/prometheus-pve-sd/pull/189/files#diff-66bff141c33041f7d400e3e742b1b6a82ede7545d1b1c09912f2965c28051eb9

Have seen it too late as well, will remove it from main. Just wanted to let you know.

**Comment by peschmae** [comment]
Damn.... yeah, that's not ideal :/
but rather this, than the config file...

**Pull request merged**
