### PR TITLE
feat: add option to authenticate with api token instead of password

### PR DESCRIPTION
**Pull request by Britaliope**
Copy-pasted from Proxmxoxer doc: 

> The API Token allows stateless interaction with the Proxmox service as well as independent permissions and more flexibility in credential lifecycle management. Abused/leaked API Tokens can be disabled independent of the account with which they are associated and multiple API Tokens can be created for a user, allowing each use its own API Token with only its needed permissions which can be independently managed.

### CODE REVIEW

**Comment by xoxys** [comment]
Thanks! Looking forward to it, please let me know if its ready to review.

**Comment by Britaliope** [comment]
> Thanks! Looking forward to it, please let me know if its ready to review.

The patch is done, but i have to invest a bit of time to add tests, i'll try to do this in the week end.

You can review it now if you have time, so if you have remarks or suggestions that will impact the tests i'll only do them only once :')

**Comment by xoxys** [comment]
Looks good to me :)

**Comment by Britaliope** [comment]
(quick updates, very busy weeks and i didn't had a minute to finish this, but i will have time this week)

**Comment by xoxys** [comment]
No worries. Thanks for your work.

**Comment by xoxys** [comment]
Closed by https://github.com/thegeeklab/prometheus-pve-sd/pull/460

@Britaliope Thanks again for your work!

**Pull request closed without merging**
